before_install: eval $(curl https://travis-perl.github.io/init) --auto
dist: trusty
language: perl
perl:
  - "5.10"
  - "5.10-thr"
  - "5.12"
  - "5.12-thr"
  - "5.14"
  - "5.14-thr"
  - "5.16"
  - "5.16-thr"
  - "5.18"
  - "5.18-thr"
  - "5.20"
  - "5.20-thr"
  - "5.22"
  - "5.22-thr"
  - "5.24"
  - "5.24-thr"
sudo: false
